# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
cache: packages
env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - NOT_CRAN="true"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

repos:
  CRAN: https://cloud.r-project.org
  GRAN: http://owi.usgs.gov/R

r_github_packages:
 - jimhester/covr
 - richfitz/remake
 - USGS-R/grithub

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev

script:
  - |
    R CMD build ${R_BUILD_ARGS} .
    PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    travis_wait 20 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}"

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
